### ISSUE TITLE
Does not compile on Ubuntu

### ISSUE THREAD

**Issue by jonasteuwen** [amspath/libisyntax#11]
Error is at this line in platform.c: `    system_info.physical_cpu_count = physical_cpu_count; // TODO(pvalkema): how to read this on Linux?`

To answer the question: It's not so easy. Do you want to know the number of physical cores available to the program (cgroups can limit this to values smaller than the system cores)? I think so, for this you need to parse `/proc/cpuinfo` to get the number of physical cores / cpus and combine this somehow with sched_getaffinity.

So, I can make it, but is it so important and can we just rely on logical cores? :-)

**Comment by alex-virodov** [comment]
I fixed the compilation issue in https://github.com/amspath/libisyntax/pull/12, just because I happened to be on Linux. I did not address the problem of actually getting proper physical/logical cpu count on linux.

**Comment by jonasteuwen** [comment]
AH, I also tried to fix it in #13.

**Comment by alex-virodov** [comment]
Please merge yours first, I can handle the minor conflicts.

**Comment by jonasteuwen** [comment]
I don't have that level of access :-).

I can confirm the ./isyntax_example runs on Ubuntu with PR #13. Note that it might be interesting to tune down the CMake version a little bit, the one we require is not available in 20.04 (and in conda only 3.22 is)

**Comment by Falcury** [comment]
> To answer the question: It's not so easy. Do you want to know the number of physical cores available to the program (cgroups can limit this to values smaller than the system cores)? I think so, for this you need to parse /proc/cpuinfo to get the number of physical cores / cpus and combine this somehow with sched_getaffinity.
>
> So, I can make it, but is it so important and can we just rely on logical cores? :-)

Thanks, this is good to know! It's true, it may not be important. For Slidescape I am also currently relying on the number of logical cores to determine the number of worker threads in the thread pool.

**Comment by alex-virodov** [comment]
It seems that we also have a similar issue on windows. I fixed it in https://github.com/amspath/libisyntax/pull/12/commits/b1cf24e1a161c6f733b7b62dbe47236346d81281

> tune down the CMake version a little bit

FYI I have no objections, I tuned it down a bit already due to CLion not supporting the latest.

**Comment by Falcury** [comment]
Just fixed it using my own commit 48e1ba67cf13b26252ef75cea48ae32ed95d3cc5. I lowered the CMake version to 3.15 (arbitrality chosen), I guess that should be good for now.
