### ISSUE TITLE
Color/contrast differences between SDK & libisyntax

### ISSUE THREAD

**Issue by jonasteuwen** [amspath/libisyntax#19]
Using Philips SDK:

<img width="484" alt="image" src="https://user-images.githubusercontent.com/2347927/233846827-2eebd4b4-9e3c-4230-a1e9-89b7ab286564.png">

Using Libisyntax
<img width="484" alt="image" src="https://user-images.githubusercontent.com/2347927/233846844-94ed22f5-18b9-415c-81ce-e2b1edad67dc.png">

I am not sure why this is happening. 
- The pipeline described by Philips also does local contrast enhancement & sharpening
- Libisyntax uses only 8 bits depth, while the paper by Philips describes not being limited to 8 bits.

This is Libisyntax + sharpening with OpenCV

<img width="484" alt="image" src="https://user-images.githubusercontent.com/2347927/233847344-7718e118-1819-4918-b3a6-8fe9bc548b34.png">

Also applying CLAHE:

<img width="484" alt="image" src="https://user-images.githubusercontent.com/2347927/233850017-a9193726-2c41-431e-b098-40c92e6c4bec.png">

That's done with this:
```python

open_cv_image = np.array(region.convert("RGB")) 
# Convert RGB to BGR 
open_cv_image = open_cv_image[:, :, ::-1].copy()

lab= cv2.cvtColor(open_cv_image, cv2.COLOR_BGR2LAB)
l_channel, a, b = cv2.split(lab)

# Applying CLAHE to L-channel
clahe = cv2.createCLAHE(clipLimit=0.4, tileGridSize=(8,8))
cl = clahe.apply(l_channel)

# merge the CLAHE enhanced L-channel with the a and b channel
limg = cv2.merge((cl,a,b))

# Converting image from LAB Color model to BGR color spcae
enhanced_img = cv2.cvtColor(limg, cv2.COLOR_LAB2BGR)


kernel =np.array([[0, -1, 0],
                   [-1, 5,-1],
                   [0, -1, 0]])
image_sharp = cv2.filter2D(src=enhanced_img, ddepth=-1, kernel=kernel)

# You may need to convert the color.
img = cv2.cvtColor(image_sharp, cv2.COLOR_BGR2RGB)
im_pil = PIL.Image.fromarray(img)
```

**Comment by jonasteuwen** [comment]
This does it in C, it seems to improve the image visually (to me)

```C
void sharpen_image(uint32_t *image, int width, int height) {
    int kernel[3][3] = {
            {0, -1, 0},
            {-1, 5, -1},
            {0, -1, 0}
    };

    uint32_t *temp_buffer = (uint32_t *)malloc(width * height * sizeof(uint32_t));

    for (int y = 1; y < height - 1; y++) {
        for (int x = 1; x < width - 1; x++) {
            int r_sum = 0, g_sum = 0, b_sum = 0, a_sum = 0;

            for (int ky = -1; ky <= 1; ky++) {
                for (int kx = -1; kx <= 1; kx++) {
                    uint32_t color = image[(y + ky) * width + (x + kx)];

                    uint8_t r = (color >> 24) & 0xFF;
                    uint8_t g = (color >> 16) & 0xFF;
                    uint8_t b = (color >> 8) & 0xFF;
                    uint8_t a = color & 0xFF;

                    r_sum += r * kernel[ky + 1][kx + 1];
                    g_sum += g * kernel[ky + 1][kx + 1];
                    b_sum += b * kernel[ky + 1][kx + 1];
                    a_sum += a * kernel[ky + 1][kx + 1];
                }
            }

            uint8_t r_output = r_sum > 255 ? 255 : (r_sum < 0 ? 0 : r_sum);
            uint8_t g_output = g_sum > 255 ? 255 : (g_sum < 0 ? 0 : g_sum);
            uint8_t b_output = b_sum > 255 ? 255 : (b_sum < 0 ? 0 : b_sum);
            uint8_t a_output = a_sum > 255 ? 255 : (a_sum < 0 ? 0 : a_sum);

            uint32_t output_color = (r_output << 24) | (g_output << 16) | (b_output << 8) | a_output;
            temp_buffer[y * width + x] = output_color;
        }
    }

    for (int y = 1; y < height - 1; y++) {
        for (int x = 1; x < width - 1; x++) {
            image[y * width + x] = temp_buffer[y * width + x];
        }
    }

    free(temp_buffer);
}

```

**Comment by Falcury** [comment]
Yeah, I did not implement the post-processing steps as described by Philips in their pipeline.
This applies for the sharpening, but also for the ICC profiles.

I think it's great if we could add them as (optional?) post-processing steps.

**Comment by Falcury** [comment]
> Libisyntax uses only 8 bits depth, while the paper by Philips describes not being limited to 8 bits.

The wavelet coefficients are 16 bits (which I guess works out well for the compression scheme). However, after the inverse wavelet transform the LL coefficients still end up transforming back into colors with regular 8 bit depth (this happens during the color space conversion).

**Comment by jonasteuwen** [comment]
Great to know! 

I wonder if we should implement the post-processing steps in the pipeline: for ML applications I don't think it matters, and for viewing applications I think you can do it in-browser or in-viewer rather than in the data pipeline.

**Comment by jonasteuwen** [comment]
@Falcury I think we all agree this effect is here, so I'll close it, I don't think it requires any action. The blurryness can also be caused by the interpolation.

**Comment by Falcury** [comment]
OK! We can reopen it later if there is a need to support the sharpening effect and ICC profiles.
