### ISSUE TITLE
GPL code included

### ISSUE THREAD

**Issue by jayvdb** [amspath/libisyntax#43]
https://github.com/amspath/libisyntax/blob/main/LICENSE.txt says BSD-3-Clause , however there is GPL code included

https://github.com/search?q=repo%3Aamspath%2Flibisyntax+GNU+General+Public+License&type=code

At least a few of those are from slidescape

https://github.com/search?q=repo%3Aamspath%2Flibisyntax+slidescape&type=code

I would dearly like to help and use libisyntax & slidescape, but can't go anywhere near code that is GPL or LGPL.

**Comment by Falcury** [comment]
Good catch, I must have missed those. My intent is for them to be permissively licensed as well. I’ll update the license of those files to match the rest.

**Comment by Falcury** [comment]
Fixed in 338f46ff50ba0bcf51e9d3c4162dbaf149100622.
