### ISSUE TITLE
Python wrapper

### ISSUE THREAD

**Issue by jonasteuwen** [amspath/libisyntax#8]
Now that we have a read_region function (#7), I suppose we can start designing a python wrapper following the API of openslide. Shall I give it a go? I also have a preliminary version to implement libisyntax as a foreign format reader for libvips.

**Comment by Falcury** [comment]
Sounds great! One question that comes to mind: will there still be added value for this once iSyntax integration is added directly to OpenSlide?

**Comment by jonasteuwen** [comment]
Probably not much, perhaps you only want to read isyntax images. Same thing if we add it to libvips (it would be able to read it through openslide as well).
Doing that will probably also come up with some suggestions for what outward facing API would be interesting.

It does solve an acute need though :-) I would think that openslide is still a way to go.

**Comment by Falcury** [comment]
If you think it could be useful, then sure I guess! We might then need to think about whether we would want to keep supporting such a wrapper long-term, or retire it it after the OpenSlide integration.

**Comment by jonasteuwen** [comment]
I’m taking a different approach. I’m implementing a foreign source for libvips, that you can easily do without directly integrating it into vips (you can register it externally) and use pyvips.On Apr 19, 2023, at 3:52 PM, Pieter Valkema ***@***.***> wrote:﻿
If you think it could be useful, then sure I guess! We might then need to think about whether we would want to keep supporting such a wrapper long-term, or retire it it after the OpenSlide integration.
